import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://dev-essensial.assist.id/login');
    await page.getByRole('img', { name: 'placeholder' }).click();
    await page.locator('body').press('ControlOrMeta+f');
    await page.getByRole('heading', { name: 'Pilih Hanya Yang Terbaik' }).click();
    await page.getByText('Assist.id adalah sistem').click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'Pelajari lebih lanjut >' }).click();
    const page1 = await page1Promise;
    await page.locator('#username').click();
    await page.locator('#username').fill('anisasecondacc24@gmail.com');
    await page.locator('[data-test="input-password"]').click();
    await page.locator('[data-test="input-password"]').click();
    await page.locator('[data-test="input-password"]').fill('12345678');
    await page.getByRole('button', { name: 'Toggle password visibility' }).click();
    await page.getByRole('button', { name: 'Toggle password visibility' }).dblclick();
    await page.locator('[data-test="login-btn"]').click();
    await page.getByText('V.3.42.0').click();
    await page.getByRole('img', { name: 'Subscription expired' }).click();
    await page.getByText('Pelayanan pasien dan').click();
    await page.getByText('Setelah perpanjangan berhasil').click();
    await page.getByText('Minta Admin untuk segera').click();
    await page.locator('div').filter({ hasText: 'Hubungi Admin Gesi [dr Frost' }).nth(4).click();
    await page.getByText('Hubungi Tim Kami').click();
    await page.getByText('Clinica LiteKlinik Anda saat ini berlangganan produk Clinica Lite1 BulanRp. 200').click();
    await page.locator('.zw-text-white.zw-opacity-80.hover\\:zw-opacity-100').click();
    await page.locator('[data-test="change-account-button-arrow"]').click();
    await page.getByRole('menuitem', { name: '- Pure Burns [Schedula] (QA)' }).click();
    await page.locator('div').filter({ hasText: 'DashboardPure Burns [Schedula]' }).nth(4).click();
    await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
    await page.locator('[data-test="sidebar-item-registrasi"]').click();
    await page.locator('[data-test="header-select-button-arrow"]').click();
    await page.getByRole('menuitem', { name: 'Pendaftaran Baru' }).press('Escape');
    await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
    await page.locator('#select-bpjsTreatment').click();
    await page.locator('html').getByRole('document').press('Escape');
    await page.locator('html').getByRole('document').click();
    await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
    await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-');
    await page.getByRole('button', { name: 'new' }).click();
    await page.locator('[data-test="input-nama-pasien"]').click();
    await page.locator('[data-test="input-nama-pasien"]').fill('PB-Skyler');
    await page.locator('.jss14790.jss14851').first().click();
    await page.locator('[data-test="input-nama-pasien"]').fill('PB-Skyler Toppenstedt');
    await page.locator('.jss14790.jss14851').first().click();
    await page.locator('[data-test="input-nama-pasien"]').press('ControlOrMeta+z');
    await page.locator('[data-test="input-nama-pasien"]').fill('PB-Skyler');
    await page.locator('.jss14790.jss14851').first().click({
        modifiers: ['ControlOrMeta']
    });
    await page.locator('[data-test="input-tempat-lahir"]').click();
    await page.locator('[data-test="input-tempat-lahir"]').fill('Toppenstedt');
    await page.locator('[data-test="date-tanggal-lahir"]').click();
    await page.getByRole('button').nth(2).click();
    await page.getByRole('button', { name: '1985' }).click();
    await page.locator('div').filter({ hasText: '1985Rab, Mei' }).nth(2).click();
    await page.getByRole('button', { name: 'OK' }).click();
    await page.getByRole('img', { name: 'Profile' }).click();
    await page.getByRole('button', { name: 'Pilih Foto' }).click();
    await page.getByRole('button', { name: 'Komputer' }).click();
    await page.locator('button').filter({ hasText: 'Pilih Foto' }).setInputFiles('Cat 10.jpg');
    await page.locator('[data-test="input-no-ktp"]').click();
    await page.locator('[data-test="input-no-ktp"]').fill('1092038129324');
    await page.locator('[data-test="input-no-ktp"]').press('ControlOrMeta+a');
    await page.locator('[data-test="input-no-ktp"]').fill('23424242433');
    await page.locator('[data-test="input-no-telepon"]').click();
    await page.locator('[data-test="input-no-telepon"]').fill('08137107995');
    await page.locator('[data-test="input-email"]').nth(1).click();
    await page.locator('div').filter({ hasText: /^Email$/ }).first().click();
    await page.locator('[data-test="input-email"]').nth(1).fill('anisasecondacc24@gmail.com');
    await page.locator('div').filter({ hasText: /^\+tambah tag$/ }).first().click();
    await page.locator('input[name="address"]').click();
    await page.locator('input[name="address"]').fill('JL ');
    await page.locator('[data-test="input-tempat-lahir"]').dblclick();
    await page.locator('[data-test="input-tempat-lahir"]').press('ControlOrMeta+c');
    await page.locator('input[name="address"]').click();
    await page.locator('input[name="address"]').fill('Jl Toppenstedt No 12253');
    await page.locator('#select-selectedProvince').click();
    await page.getByRole('option', { name: 'BENGKULU' }).click();
    await page.locator('.jss14787.jss14788').click();
    await page.locator('#select-selectedKecamatan').click();
    await page.locator('.jss14787.jss14788').click();
    await page.locator('#select-selectedKabupaten').click();
    await page.getByRole('option', { name: 'KAB. BENGKULU UTARA' }).click();
    await page.locator('#select-selectedKabupaten').click();
    await page.locator('.jss14787.jss14788').click();
    await page.locator('#select-selectedKecamatan').click();
    await page.getByRole('option', { name: 'BATIK NAU' }).click();
    await page.locator('#select-selectedKelurahan').click();
    await page.getByRole('option', { name: 'BATIK NAU' }).click();
    await page.locator('input[name="postcode"]').click();
    await page.locator('input[name="postcode"]').fill('234232');
    await page.getByRole('button', { name: 'simpan' }).click();
    await page.getByText('Laki - laki').click();
    await page.locator('div:nth-child(4) > .jss3934 > .jss3935').first().click();
    await page.locator('.jss44846').click();
    await page.locator('#select-doctorName').click();
    await page.getByRole('option', { name: 'BN-Maxwell' }).click();
    await page.locator('div').filter({ hasText: 'Jenis Perawatan *Rawat Jalan' }).nth(5).click();
    await page.locator('div').filter({ hasText: 'Jenis Perawatan *Rawat Jalan' }).nth(5).click();
    await page.getByRole('option', { name: 'Rawat Inap' }).click();
    await page.locator('#select-room').click();
    await page.locator('.jss48616').click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').dblclick();
    await page.getByRole('button').first().click();
    await page.locator('[data-test="sidebar-item-settings"]').click();
    await page.locator('[data-test="close-global-tooltip"]').click();
    await page.locator('[data-test="sidebar-item-settings"]').press('ControlOrMeta+f');
    await page.locator('[data-test="sidebar-item-settings"]').press('Escape');
    await page.locator('div').filter({ hasText: 'Faktur Pajak tidak dapat' }).nth(4).click();
    await page.locator('[data-test="sidebar-item-registrasi"]').click();
    await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
    await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
    await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-');
    await page.getByRole('button', { name: 'PB-Skyler 09-05-1985,' }).click();
    await page.locator('div').filter({ hasText: 'Jenis Perawatan *Rawat Jalan' }).nth(5).click();
    await page.locator('div').filter({ hasText: 'Jenis Perawatan *Rawat Jalan' }).nth(5).click();
    await page.getByRole('option', { name: 'Rawat Inap' }).click();
    await page.locator('#select-room').click();
    await page.locator('#select-room').dblclick();
    await page.locator('#select-doctorName').click();
    await page.locator('#select-doctorName').click();
    await page.locator('.jss70229').click();
    await page.locator('[data-test="input-complaint"]').click();
    await page.locator('[data-test="input-complaint"]').fill('Dropdown ranap tersedia, namun Tipe Kamar\n');
    await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
    await page.locator('[data-test="input-complaint"]').press('ArrowRight');
    await page.locator('[data-test="input-complaint"]').fill('Dropdown ranap tersedia, namun Tipe Kamar');
    await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
    await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
    await page.locator('[data-test="input-complaint"]').fill('Dropdown ranap tersedia, namun tetap dicegah krn Tipe Kamar');
    await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+ArrowRight');
    await page.locator('[data-test="input-complaint"]').fill('Dropdown ranap tersedia, namun tetap dicegah krn Tipe Kamar blank ,dan tidak bisa diinput dari Setting krn menu-nya juga tidak tersedia. apakah sebaiknya di hide?');
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.getByRole('button', { name: 'Batal' }).click();
    await page.locator('div').filter({ hasText: /^AntriCepat$/ }).nth(2).click();
    await page.locator('[data-test="menu-rawat-jalan-poli"]').click();
    await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
    await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
    await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-');
    await page.getByRole('button', { name: 'PB-Skyler 09-05-1985,' }).click();
    await page.getByRole('button', { name: 'Rawat Jalan' }).click();
    await page.locator('.jss173554').click();
    await page.locator('#select-doctorName').click();
    await page.getByRole('option', { name: 'BN-Maxwell' }).click();
    await page.locator('[data-test="input-complaint"]').click();
    await page.locator('[data-test="input-complaint"]').fill('Test kunjungan');
    await page.locator('[data-test="input-procedure-plan"]').click();
    await page.locator('[data-test="input-procedure-plan"]').fill('Rencana 01');
    await page.locator('[data-test="input-kondisi-awal-pasien"]').click();
    await page.locator('[data-test="input-kondisi-awal-pasien"]').fill('Kondisi Pasien 01');
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.getByText('Rawat Jalan PoliExport event').click();
    await page.getByRole('cell', { name: '/05/2026, 10:34' }).click();
    await page.getByRole('button', { name: 'confirmed' }).click();
    await page.locator('div:nth-child(9) > .jss209426').click();
    await page.getByRole('button').first().click();
    await page.getByText('Confirmed').click();
    await page.getByRole('button', { name: 'confirmed' }).click();
    await page.getByRole('button', { name: 'succeed' }).click();
    await page.locator('.jss209570').click();
    await page.locator('div').filter({ hasText: 'RegistrationPure Burns [' }).nth(4).click();
    await page.locator('[data-test="sidebar-item-kasir"]').click();
    await page.locator('[data-test="sidebar-item-settings"]').click();
    await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
    await page.getByRole('button', { name: 'Tambah Prosedur' }).click();
    await page.getByText('Nama Prosedur *Nama Layanan').click();
    await page.locator('[data-test="input-namaProsedur-0"]').click();
    await page.locator('[data-test="input-namaProsedur-0"]').fill('PB-P-Dialysis');
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('B');
    await page.getByRole('menuitem', { name: 'BN-Maxwell' }).click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('Bn');
    await page.getByText('BN-Gilbert').click();
    await page.getByText('BN-Gilbert').click();
    await page.getByText('BN-Gilbert').click();
    await page.getByText('BN-Gilbert').click();
    await page.locator('div').filter({ hasText: /^Tambah Form Prosedur$/ }).click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('');
    await page.getByText('BN-Gilbert').click();
    await page.getByRole('menuitem', { name: 'BN-Gilbert' }).click();
    await page.locator('[data-test="input-hargaProsedur-0"]').click();
    await page.locator('[data-test="input-hargaProsedur-0"]').fill('Rp40.0000');
    await page.getByRole('button', { name: 'Tambah Form Prosedur' }).click();
    await page.locator('[data-test="button-deleteProcedure-1"]').click();
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.locator('.jss1980.jss1981.jss1988.jss1998.jss210190').click();
    await page.getByRole('button', { name: 'Tambah Prosedur' }).click();
    await page.locator('html').getByRole('document').press('Escape');
    await page.getByRole('button', { name: 'Tambah Prosedur' }).click();
    await page.locator('[data-test="button-deleteProcedure-1"]').click();
    await page.locator('[data-test="button-deleteProcedure-0"]').click();
    await page.getByRole('button').filter({ hasText: /^$/ }).click();
    await page.getByRole('button', { name: 'Import Prosedur Import Harga' }).click();
    await page.getByText('Katalog Harga Prosedur').nth(1).click();
    await page.getByRole('button', { name: 'Tambah Prosedur' }).click();
    await page.locator('[data-test="input-namaProsedur-0"]').click();
    await page.locator('[data-test="input-namaProsedur-0"]').fill('PB-Venogram');
    await page.locator('[data-test="input-namaProsedur-0"]').press('Alt+ArrowLeft');
    await page.locator('[data-test="input-namaProsedur-0"]').fill('PB-P-Venogram');
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="input-hargaProsedur-0"]').click();
    await page.locator('[data-test="input-hargaProsedur-0"]').press('Shift+ArrowLeft');
    await page.locator('[data-test="input-hargaProsedur-0"]').fill('Rp30.0000');
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').fill('Anti');
    await page.getByText('99.28 Injection or infusion').click();
    await page.getByText('99.28 Injection or infusion').click();
    await page.getByText('Injection of antidote').click();
    await page.getByText('Injection of antidote').click();
    await page.locator('.jss1980.jss1981.jss2011').click();
    await page.locator('div').filter({ hasText: /^ICD 9 CM$/ }).first().click();
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').fill('Ant');
    await page.getByText('00.14 Injection or infusion').dblclick();
    await page.getByText('CatatanBahan Habis PakaiHide').click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('BN-');
    await page.getByText('BN-Maxwell').click();
    await page.getByText('BN-Gilbert').click();
    await page.getByText('BN-Gilbert').dblclick();
    await page.getByText('BN-Gilbert').dblclick();
    await page.getByRole('menuitem', { name: 'BN-Maxwell' }).click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('Bn');
    await page.getByText('BN-Gilbert').click();
    await page.getByText('BN-Gilbert').dblclick();
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-icd9cm-0"] [data-test="autocomplete-input"]').fill('Anti');
    await page.getByRole('menuitem', { name: '99.22 Injection of other anti' }).click();
    await page.locator('[data-test="parent-autocomplete-bahanHabisPakai-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-bahanHabisPakai-0"] [data-test="autocomplete-input"]').fill('Tiss');
    await page.locator('[data-test="parent-autocomplete-bahanHabisPakai-0"] [data-test="autocomplete-input"]').press('ControlOrMeta+a');
    await page.locator('[data-test="parent-autocomplete-bahanHabisPakai-0"] [data-test="autocomplete-input"]').click();
    await page.locator('[data-test="parent-autocomplete-bahanHabisPakai-0"] [data-test="autocomplete-input"]').fill('');
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.getByRole('button', { name: 'Settings' }).nth(2).click();
    await page.getByText('Edit data prosedur').click();
    await page.locator('[data-test="input-catatan-0"]').click();
    await page.locator('[data-test="input-namaProsedur-0"]').click();
    await page.locator('[data-test="input-namaProsedur-0"]').fill('PB-P-Venogram []');
    await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowLeft');
    await page.locator('[data-test="input-namaProsedur-0"]').fill('PB-P-Venogram [ICD9]');
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.locator('[data-test="sidebar-item-kasir"]').click();
    await page.locator('#cashAddBtn').click();
    await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).click();
    await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('PB-');
    await page.getByRole('button', { name: 'PB-P-Dialysis' }).click();
    await page.getByRole('button', { name: 'PB-P-Venogram [ICD9]' }).click();
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').click();
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('02');
    await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').click();
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('21');
    await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('ArrowDown');
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').click();
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('');
    await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').click();
    await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('01');
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').click();
    await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('02');
    await page.getByRole('button').nth(3).click();
    await page.locator('.jss213307').click();
    await page.getByRole('button').nth(5).click();
    await page.getByRole('button').nth(5).click();
    await page.getByRole('option', { name: 'Fix' }).click();
    await page.locator('[data-test="kasir-item-1"] [data-test="discount-value-input"]').click();
    await page.locator('[data-test="kasir-item-1"] [data-test="discount-value-input"]').fill('Rp100.0000');
    await page.locator('[data-test="kasir-item-1"] [data-test="discount-value-input"]').press('ControlOrMeta+a');
    await page.locator('[data-test="kasir-item-1"] [data-test="discount-value-input"]').fill('Rp5.0000');
    await page.locator('[data-test="input-bayar-langsung"]').click();
    await page.locator('[data-test="input-bayar-langsung"]').fill('Rp100.0000');
    await page.locator('[data-test="input-dibayar-oleh-langsung"]').click();
    await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Pasien Random OTC');
    await page.locator('.jss213176').click();
    await page.locator('div').filter({ hasText: /^Apotek$/ }).nth(5).click();
    await page.getByRole('button').nth(1).click();
    await page.getByRole('button').nth(1).click();
    await page.locator('.jss212768.jss212769').click();
    await page.locator('[data-test="button-bayar-langsung"]').click();
    await page.getByRole('button', { name: 'Kertas Struk Biasa' }).click();
    await page.getByRole('button').first().click();
    await page.locator('[data-test="sidebar-item-profile"]').click();
    await expect(page.getByRole('heading', { name: 'Pastikan Faskes Anda' })).toBeVisible();
    await page.getByRole('heading', { name: 'Informasi Fasilitas Kesehatan' }).click();
    await page.getByText('Kelengkapan informasi faskes').click();
    await page.getByText('Kelengkapan profil Anda 85%').click();
    await page.getByRole('button', { name: 'Edit' }).click();
    await page.locator('[data-test="input-nomor-telepon"]').click();
    await page.locator('[data-test="input-nomor-telepon"]').fill('0761292939');
    await page.locator('[data-test="button-tambah-nomor-telepon"]').click();
    await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
    await page.locator('[data-test="input-nitku"]').click();
    await page.locator('[data-test="input-nitku"]').fill('NITKU Burns');
    await page.locator('[data-test="input-deskripsi"]').click();
    await page.locator('[data-test="input-nitku"]').fill('NITKU BurnsD');
    await page.locator('[data-test="input-deskripsi"]').fill('Desc');
    await page.locator('[data-test="button-simpan-informasi-dasar"]').click();
    await page.locator('[data-test="button-simpan-informasi-dasar"]').click();
    await page.locator('[data-test="button-simpan-informasi-dasar"]').click();
    await page.getByRole('button', { name: 'Alamat' }).click();
    await page.getByRole('button', { name: 'Visi Misi' }).click();
    await page.locator('.jss213849').first().click();
    await page.locator('[data-test="input-visi"]').fill('');
    await page.locator('[data-test="input-visi"]').click();
    await page.getByRole('button', { name: 'Visi Misi', exact: true }).click();
    await page.getByRole('button', { name: 'Informasi Dasar' }).click();
    await page.getByRole('button', { name: 'Visi Misi' }).click();
    await page.locator('#mainLayoutContainer').click();
    await page.locator('[data-test="sidebar-item-kasir"]').click();
    await page.locator('[data-test="sidebar-item-profile"]').click();
    await page.getByRole('button', { name: 'Edit' }).click();
    await page.getByRole('button', { name: 'Visi Misi' }).click();
    await page.getByRole('button', { name: 'Alamat' }).click();
    await page.locator('div:nth-child(6) > .jss214976').click();
    await page.getByRole('option', { name: 'WIB' }).click();
    await page.locator('[data-test="button-simpan-alamat"]').click();
    await page.getByRole('button', { name: 'Metode Pembayaran' }).click();
    await page.getByRole('button', { name: 'Photo' }).click();
    await page.locator('[data-test="dropzone-upload-photo"]').click();
    await page.locator('body').setInputFiles(['Cat 10.jpg', 'Cat 11.jpg', 'Cat 12.jpg']);
    await page.getByRole('img', { name: 'error' }).nth(2).click();
    await page.getByRole('img', { name: 'error' }).nth(2).click();
    await page.getByRole('button', { name: 'Jadikan Profile Picture' }).nth(2).click();
    await page.getByRole('button', { name: 'Profile Picture', exact: true }).click();
    await page.locator('.jss215648').click();
    await page.locator('[data-test="dropzone-upload-photo"]').click();
    await page.getByRole('button', { name: 'Fasilitas' }).click();
    await page.getByRole('button', { name: 'Photo' }).click();
    await page.locator('[data-test="dropzone-upload-photo"]').click();
    await page.locator('body').setInputFiles('Cat 05.jpg');
    await page.locator('#mainLayoutContainer').click();
    await page.getByRole('button', { name: 'Fasilitas' }).click();
    await page.getByText('Ambulans').click();
    await page.locator('label').filter({ hasText: 'Ambulans' }).check();
    await page.getByRole('checkbox', { name: 'Insalasi Gawat Darurat' }).check();
    await page.getByText('AmbulansMushalaKantinTempat').click();
    await page.getByRole('checkbox', { name: 'Ruang Operasi' }).check();
    await page.getByRole('checkbox', { name: 'Kantin' }).check();
    await page.getByRole('checkbox', { name: 'Ruang Bayi' }).check();
    await page.locator('[data-test="button-simpan-fasilitas"]').click();
    await page.getByRole('button', { name: 'Jam Operational' }).click();
    await page.locator('[data-test="checkbox-handlechangeallday"]').check();
    await page.locator('[data-test="button-simpan-operational-time"]').click();
    await page.locator('[data-test="button-simpan-operational-time"]').click();
    await page.getByRole('button', { name: 'Organisasi' }).click();
    await page.getByRole('button', { name: 'Jam Operational' }).click();
    await page.getByRole('button', { name: 'Poli' }).click();
    await page.getByText('Poli *Pilih Poli').click();
    await page.getByText('Pilih PoliUmumLabGawat Darurat').click();
    await page.getByRole('button', { name: 'Lab' }).click();
    await page.getByRole('option', { name: 'Umum' }).click();
    await page.locator('div').filter({ hasText: /^Senin$/ }).click();
    await page.locator('[data-test="checkboxHandleHoliday"]').first().check();
    await page.locator('[data-test="checkboxHandleHoliday"]').nth(1).check();
    await page.locator('div').filter({ hasText: /^Tutup$/ }).nth(2).click();
    await page.locator('[data-test="parent-time-picker-monday-0"]').getByRole('textbox').click();
    await page.getByRole('menu').click();
    await page.getByRole('menu').click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').first().click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').first().click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.locator('[data-test="parent-time-picker-monday-0"]').getByRole('textbox').click();
    await page.getByRole('menu').click();
    await page.locator('div').filter({ hasText: ':30' }).nth(4).click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.locator('div:nth-child(2) > .jss216366 > .jss51253 > .jss216388 > .jss2268').first().click();
    await page.getByRole('menu').click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').click();
    await page.locator('html').getByRole('document').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.locator('.jss1981.jss2020.jss2025').click();
    await page.locator('[data-test="parent-time-picker-monday-0"]').getByRole('textbox').click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.locator('div:nth-child(6) > .jss1981.jss1983.jss1988 > .jss1981.jss2020 > .jss1980 > div > .jss216366 > .jss51253 > .jss51263').first().click();
    await page.getByRole('menu').click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('heading', { name: '18' }).dblclick();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.locator('html').getByRole('document').click();
    await page.getByText(':21000510152025303540455055CancelOK').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.locator('[data-test="parent-time-picker-tuesday-0"]').getByRole('textbox').click();
    await page.getByRole('menu').click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('heading', { name: '18' }).click();
    await page.getByRole('menu').click();
    await page.getByRole('menu').click();
    await page.getByRole('menu').click();
    await page.getByRole('menu').click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').click();
    await page.getByRole('menu').press('Escape');
    await page.getByRole('button', { name: 'Umum' }).click();
    await page.getByRole('option', { name: 'Lab' }).click();
    await page.locator('.jss1981.jss2020.jss2025').click();
    await page.getByRole('button', { name: 'Organisasi' }).click();
    await page.locator('.jss1981.jss2020.jss2025').click();
    await page.locator('[data-test="sidebar-item-message-center"]').click();
    await page.locator('[data-test="sidebar-item-office"]').click();
    await page.getByRole('heading', { name: 'Daftar Appointment Pasien' }).click();
    await page.getByText('Show Filters').click();
    await page.locator('html').getByRole('document').press('Escape');
    await page.getByRole('button', { name: 'Pasien' }).click();
    await page.getByRole('button', { name: 'Data Pasien' }).click();
    await page.locator('.jss2265.jss2396.jss217370').first().click();
    await page.locator('[data-test="input-nama-pasien"]').press('Escape');
    await page.locator('[data-test="sidebar-item-settings"]').click();
    await page.locator('[data-test="sidebar-item-settings"]').click();
    await page.locator('[data-test="sidebar-item-layananTambahn"]').click();
    await page.locator('[data-test="sidebar-item-pertanyaan"]').click();
    await page.locator('[data-test="sidebar-item-settings"]').click();
    await page.locator('[data-test="sidebar-item-settings"]').press('ControlOrMeta+f');
    await page.getByRole('button', { name: 'Katalog Paket Prosedur' }).click();
    await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
    await page.getByRole('button', { name: 'Import Prosedur Import Harga' }).click();
    await page.getByRole('button', { name: 'Import Prosedur Import Harga' }).click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').click();
    await page.locator('html').getByRole('document').press('Escape');
    await page.locator('[data-test="sidebar-item-office"]').click();
    await page.locator('[data-test="sidebar-item-profile"]').click();
    await page.getByRole('button', { name: 'Edit' }).click();
    await page.getByRole('button', { name: 'Metode Pembayaran' }).click();
    await page.locator('div').filter({ hasText: /^Tunai$/ }).nth(1).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
    await page.getByText('Aesta tunai').click();
    await page.getByRole('menuitem', { name: 'Debit Mandiri' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
    await page.getByRole('menuitem', { name: 'Aesta tunai' }).click();
    await page.getByRole('button', { name: 'Debit Mandiri' }).click();
    await page.getByRole('button', { name: 'Debit Mandiri' }).click();
    await page.getByRole('button', { name: 'Debit Mandiri' }).click();
    await page.getByRole('button', { name: 'Debit Mandiri' }).dblclick();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
    await page.getByText('"><script src=https://milaya.').click();
    await page.getByText('Aesta final test').click();
    await page.getByText('Aesta final test').dblclick();
    await page.getByText('YAP').dblclick();
    await page.getByText('YAP').dblclick();
    await page.getByRole('button', { name: 'Debit Mandiri' }).click();
    await page.getByRole('button', { name: 'Debit Mandiri' }).dblclick();
    await page.locator('.jss1981.jss2020.jss2025').click();
    await page.getByRole('button', { name: 'Metode Pembayaran' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
    await page.getByText('Debit Bank BCA').click();
    await page.getByRole('menuitem', { name: 'Aesta tunai' }).click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
    await page.locator('#downshift-61-item-5').getByText('Aesta tunai').click();
    await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
    await page.getByText('Debit Bank BCA').click();
    await page.locator('#downshift-61-item-6').getByText('Debit Bank BCA').click();
    await page.getByRole('button', { name: 'Debit Bank BCA' }).click();
    await page.getByRole('button', { name: 'Debit Bank BCA' }).click();
    await page.getByRole('button', { name: 'Debit Bank BCA' }).click();
    await page.getByRole('button', { name: 'Debit Bank BCA' }).click();
    await page.getByRole('button', { name: 'Import Prosedur Import Harga' }).click();
    await page.getByRole('checkbox', { name: 'PT. Garudafood' }).check();
    await page.getByRole('checkbox', { name: 'PT. Budi Rides Cemerlang' }).check();
    await page.getByRole('checkbox', { name: 'ACA Insurance' }).check();
    await page.getByRole('checkbox', { name: 'Berdikari Insurance' }).check();
    await page.getByRole('checkbox', { name: 'Berdikari Insurance' }).uncheck();
    await page.getByRole('checkbox', { name: 'Prudential Life Insurance' }).check();
    await page.locator('div').filter({ hasText: /^Tipe Metode BayarKamu bisa pilih tipe metode bayar yang ingin kamu buat\.$/ }).click();
    await page.getByRole('button', { name: 'Proses' }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
    const download = await downloadPromise;
    await page.getByRole('button').first().click();
    const download1Promise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
    const download1 = await download1Promise;
    await page.getByRole('button').first().click();
    const download2Promise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
    const download2 = await download2Promise;
    await page.locator('html').getByRole('document').click();
    const download3Promise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
    const download3 = await download3Promise;
    await page.getByRole('button').first().click();
    await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).click();
    await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Katalog Harga Prosedur (1).xlsx');
    await page.getByRole('button').first().click();
    await page.getByRole('button', { name: 'Katalog Paket Prosedur' }).click();
    await page.locator('html').getByRole('document').click();
    await page.getByRole('button', { name: 'Batal' }).click();
    await page.locator('.jss222222 > .jss2265').first().click();
    await page.getByRole('button').first().click();
    await page.getByRole('button', { name: 'Close' }).click();
    await page.locator('.jss222388').click();
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.getByRole('button', { name: 'Saya Yakin' }).click();
    await page.getByRole('button', { name: 'Settings' }).nth(1).click();
    await page.getByText('Edit data prosedur').click();
    await page.locator('.jss222489').click();
    await page.goto('https://dev-essensial.assist.id/cashier');
    await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('BN');
    await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
    await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('PB-');
    await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
    await page.locator('[data-test="quantity-input"]').fill('1');
    await page.locator('#cashAddBtn').press('ControlOrMeta+-');
    await page.goto('https://dev-essensial.assist.id/office');
    await page.locator('input[name="invoiceNo"]').fill('INV-OP-01');
    await page.locator('input[name="itemName"]').fill('Beli Sapu');
    await page.getByRole('textbox').nth(2).fill('Rp. 3.0000');
    await page.locator('textarea[name="freeText"]').fill('Sapu Nagata');
    await page.goto('https://dev-essensial.assist.id/settings');
    await page.locator('[data-test="sidebar-item-settings"]').press('ControlOrMeta+f');
    await page.goto('https://dev-essensial.assist.id/office');
    await page.locator('[data-test="sidebar-item-office"]').press('ControlOrMeta+f');
    await page.locator('[data-test="sidebar-item-office"]').press('Escape');
    await page.goto('https://dev-essensial.assist.id/settings');
    await page.locator('[data-test="input-packageName-0"]').fill('PB-Paket ');
    await page.locator('[data-test="parent-autocomplete-procedure-0-0"] [data-test="autocomplete-input"]').fill('PB');
    await page.locator('[data-test="parent-autocomplete-procedure-0-0"] [data-test="autocomplete-input"]').press('ArrowDown');
    await page.locator('[data-test="parent-autocomplete-procedure-0-0"] [data-test="autocomplete-input"]').press('Enter');
    await page.locator('[data-test="autocomplete-input"]').fill('PB');
    await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
    await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
    await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
    await page.locator('[data-test="autocomplete-input"]').press('Enter');
    await page.locator('[data-test="input-packageName-0"]').fill('PB-Paket Dia + Veno');
    await page.locator('[data-test="input-procedureQuantity-0-0"]').press('Shift+ArrowLeft');
    await page.locator('[data-test="input-procedureQuantity-0-0"]').fill('2');
    await page.locator('[data-test="input-procedureQuantity-0-1"]').press('Shift+ArrowLeft');
    await page.locator('[data-test="input-procedureQuantity-0-1"]').fill('2');
    await page.locator('[data-test="input-packageName-0"]').fill('PB-Paket Dia + Veno 22');
    await page.locator('[data-test="input-packageDuration-0"]').press('Shift+ArrowLeft');
    await page.locator('[data-test="input-packageDuration-0"]').fill('40.00');
    await page.locator('[data-test="input-packagePrice-0"]').fill('Rp2.0000');
    await page.locator('[data-test="input-packagePrice-0"]').press('ControlOrMeta+a');
    await page.locator('[data-test="input-packagePrice-0"]').fill('Rp100.0000');
});